service: marktplaats-backend

provider:
  name: aws
  runtime: python3.11
  region: eu-west-1
  memorySize: 512
  timeout: 30
  environment:
    S3_BUCKET: marktplaatser-images
    MARKTPLAATS_CLIENT_ID: ${env:MARKTPLAATS_CLIENT_ID}
    MARKTPLAATS_CLIENT_SECRET: ${env:MARKTPLAATS_CLIENT_SECRET}
    FRONTEND_DOMAIN: marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com
    TAXONOMY_KNOWLEDGE_BASE_ID: PORZ8IEECD
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rekognition:DetectLabels
            - rekognition:DetectText
          Resource: "*"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:GetBucketLocation
            - s3:ListBucket
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::marktplaatser-images
            - arn:aws:s3:::marktplaatser-images/*
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
            - bedrock:RetrieveAndGenerate
            - bedrock:GetInferenceProfile
            - bedrock:Retrieve
            - bedrock-agent-runtime:RetrieveAndGenerate
            - bedrock-agent-runtime:Retrieve
          Resource: "*"
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:eu-west-1:*:table/marktplaats-user-tokens
            - arn:aws:dynamodb:eu-west-1:*:table/marktplaats-draft-listings
            - arn:aws:dynamodb:eu-west-1:*:table/marktplaats-draft-listings/index/*

functions:
  generateListing:
    handler: src/marktplaats_backend/generate_listing_lambda.lambda_handler
    timeout: 60
    memorySize: 1024
    events:
      - http:
          path: generate-listing
          method: post
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          
  createAdvertisement:
    handler: src/marktplaats_backend/create_advertisement_lambda.lambda_handler
    timeout: 60
    events:
      - http:
          path: create-advertisement
          method: post
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: create-advertisement
          method: options
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          
  oauthAuthorize:
    handler: src/marktplaats_backend/oauth_authorize_lambda.lambda_handler
    events:
      - http:
          path: oauth/authorize
          method: get
          cors: true
          
  oauthCallback:
    handler: src/marktplaats_backend/oauth_callback_lambda.lambda_handler
    events:
      - http:
          path: oauth/callback
          method: get
          cors: true
          
  getCategories:
    handler: src/marktplaats_backend/categories_lambda.lambda_handler
    events:
      - http:
          path: categories
          method: get
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
            
  listAdvertisements:
    handler: src/marktplaats_backend/list_advertisements_lambda.lambda_handler
    events:
      - http:
          path: list-advertisements
          method: get
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: list-advertisements
          method: options
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
            
  getAdvertisementImages:
    handler: src/marktplaats_backend/get_advertisement_images_lambda.lambda_handler
    events:
      - http:
          path: advertisement-images/{id}
          method: get
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: advertisement-images/{id}
          method: options
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
            
  manageAdvertisement:
    handler: src/marktplaats_backend/manage_advertisement_lambda.lambda_handler
    events:
      - http:
          path: manage-advertisement/{id}
          method: get
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: manage-advertisement/{id}
          method: patch
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: manage-advertisement/{id}
          method: delete
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: manage-advertisement/{id}
          method: options
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
            
  draftManagement:
    handler: src/marktplaats_backend/draft_management_lambda.lambda_handler
    events:
      # List drafts: GET /drafts
      - http:
          path: drafts
          method: get
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: drafts
          method: options
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      
      # Create draft: POST /drafts
      - http:
          path: drafts
          method: post
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      
      # Get specific draft: GET /drafts/{id}
      - http:
          path: drafts/{id}
          method: get
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: drafts/{id}
          method: options
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      
      # Update draft: PATCH /drafts/{id}
      - http:
          path: drafts/{id}
          method: patch
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      
      # Delete draft: DELETE /drafts/{id}
      - http:
          path: drafts/{id}
          method: delete
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      
      # Validate draft: POST /drafts/{id}/validate
      - http:
          path: drafts/{id}/validate
          method: post
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      
      # Publish draft: POST /drafts/{id}/publish
      - http:
          path: drafts/{id}/publish
          method: post
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: drafts/{id}/publish
          method: options
          cors:
            origin: 'http://marktplaats-frontend-simple-prod-website.s3-website.eu-west-1.amazonaws.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

resources:
  Resources:
    UserTokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: marktplaats-user-tokens
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    DraftListingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: marktplaats-draft-listings
        AttributeDefinitions:
          - AttributeName: draftId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: draftId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
