service: marktplaats-backend

provider:
  name: aws
  runtime: python3.11
  region: eu-west-1
  memorySize: 512
  timeout: 30
  environment:
    S3_BUCKET: marktplaatser-images
    MARKTPLAATS_CLIENT_ID: ${env:MARKTPLAATS_CLIENT_ID}
    MARKTPLAATS_CLIENT_SECRET: ${env:MARKTPLAATS_CLIENT_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rekognition:DetectLabels
            - rekognition:DetectText
          Resource: "*"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:ListBucket
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::marktplaatser-images
            - arn:aws:s3:::marktplaatser-images/*
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
          Resource: "*"

functions:
  generateListing:
    handler: src/marktplaats_backend/generate_listing_lambda.lambda_handler
    events:
      - http:
          path: generate-listing
          method: post
          cors: true
          
  createAdvertisement:
    handler: src/marktplaats_backend/create_advertisement_lambda.lambda_handler
    timeout: 60
    events:
      - http:
          path: create-advertisement
          method: post
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
