// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/26/2025, 3:23:52 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/sander.vandenberg/src/marktplaatser/marktplaats-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sander.vandenberg/src/marktplaatser/marktplaats-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sander.vandenberg/src/marktplaatser/marktplaats-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sander.vandenberg/src/marktplaatser/marktplaats-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sander.vandenberg/src/marktplaatser/marktplaats-frontend/plugins/**/*.{js,ts,mjs}","/Users/sander.vandenberg/src/marktplaatser/marktplaats-frontend/composables/**/*.{js,ts,mjs}","/Users/sander.vandenberg/src/marktplaatser/marktplaats-frontend/utils/**/*.{js,ts,mjs}","/Users/sander.vandenberg/src/marktplaatser/marktplaats-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sander.vandenberg/src/marktplaatser/marktplaats-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sander.vandenberg/src/marktplaatser/marktplaats-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sander.vandenberg/src/marktplaatser/marktplaats-frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;